#! /usr/bin/env bash

PREFIX=/usr/local/bin
ORGNAME="18f"

if git status 2>&1 | grep fatal > /dev/null; then
  CURL=true
  cd /tmp || exit 1
  git clone https://github.com/18f/18f-cli
  cd 18f-cli || exit 1
fi

echo "Installing main $ORGNAME command"
cp main $PREFIX/$ORGNAME

cd bin || exit 1
BINS=$(find *)
for bin in $BINS; do
  echo "Installing $bin subcommand"
  cp $bin $PREFIX/$ORGNAME-$bin
done

if [[ $CURL ]]; then
  cd /tmp || exit 1
  rm -rf 18f-cli
fi
