#! /usr/bin/env bash

cd $(git rev-parse --show-toplevel)

FILE=$(find . -name latest-commit.txt)

if [[ -n $FILE ]]; then
  git rev-parse --abbrev-ref HEAD > $FILE
  git rev-parse HEAD >> $FILE
  git add $FILE
else
  :
fi
