#! /usr/bin/env bash

cd "$(git rev-parse --show-toplevel)" || exit 1

FILE=$(find . -name latest-commit.txt)

if [[ -n $FILE ]]; then
  git rev-parse --abbrev-ref HEAD > $FILE
  git rev-parse HEAD >> $FILE
else
  :
fi
